# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Build And Test Client CI

on:
  push:
    branches: [ main ]
    paths: ['client/**', '.github/workflows/client-build-and-test.yml']
  pull_request:
    branches: [ main ]
    paths: ['client/**', '.github/workflows/client-build-and-test.yml']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: client

    strategy:
      matrix:
        node-version: [14.x, 16.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: npm ci
        run: npm ci
      
      - name: npm run build
        run: npm run build --if-present
      
      - name: npm test
        run: npm test
